Azure/azure-functions-kafka-extension

samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleConsumer/LocalSchemaRegistry.cs
samples/dotnet/ConsoleConsumer/MagicAvroDeserializer.cs
samples/dotnet/ConsoleConsumer/Program.cs
samples/dotnet/ConsoleProducer/ConsoleProducer.csproj
samples/dotnet/ConsoleProducer/ProtoBufSerializer.cs
samples/dotnet/KafkaFunctionSample/.vscode/settings.json
samples/dotnet/KafkaFunctionSample/.vscode/tasks.json
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/FunctionExecutorBase.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/LocalSchemaRegistry.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/ProtobufDeserializer.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/KafkaListenerForTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests.csproj

- Use Confluent.Kafka 1.0.0-RC2 from 1.0.0-beta3 (as recommended on their repo)
- Target .NET Core 2.1 instead of .NET 2.2
Fixes #33

Update to Confluent.Kafka 1.0.0-RC2

---

samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleConsumer/Program.cs
samples/dotnet/KafkaFunctionSample/AvroGenericTriggers.cs
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/IKafkaProducer.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAsyncCollector.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducer.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj

Changes:
* Producer sends messages in batches. Initial version had a call for each produced message. Now messages are sent in batches.
* Removed direct dependency to librdkafka.redist
* Change all sample function code to consume events in batches
Part of #11

Producer sends messages in batches

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerAvro.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerFactory.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerProtoBuf.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/KafkaListenerForTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs

Resolves items 1 & 2 in #44 by doing the following:
* Creating a `KafkaListenerFactory` to be used by `KafkaTriggerAttributeBindingProvider` which serves a couple of purposes:
1. Abstracts away knowledge of how to create specific listeners
1. Abstracts away all the reflection gymnastics
* Creates `KafkaListenerAvro` and `KafkaListenerProtoBuf` for the Avro & Google Protocol Buffer implementations of listeners, respectively. This allows us to
* Nixes all knowledge of other listeners from `KafkaListener` and use it as a "base" implementation of a Kafka listener
* Modifies tests accordingly

Reworking Listener creating in to a Factory pattern. 

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerFactory.cs

KafkaListenerFactory was not identifying GenericRecord as an Avro typed value.
Expected behaviour was to create a KafkaListenerAvro type, however a KafkaListener was created.

Fix bug in KafkaListenerFactory when trigger is using an Avro GenericRecord

---

README.md
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducer.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Constants.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTestFixture.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaOutputFunctions.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/MultiItemTrigger.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/MultiItemTriggerTenPartitions.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/MyProtobufTrigger.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/MyRecordAvroTrigger.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/SingleItemTrigger.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/SingleItemTriggerTenPartitions.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/StringTopicWithLongKeyAndTenPartitionsTrigger.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/appsettings.tests.json
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/start-kafka-test-environment.sh

Changes:
* Fix logging of failed produced messages
* Add testing documentation
* Moved partition creation to test fixture to simplify running end to end tests locally
* Add support to run end to end tests against a Kafka broker located in a different place than localhost:9092
Fixes #46 
Part of #31

Add testing documentation

---

samples/dotnet/KafkaFunctionSample/AvroSpecificTriggers.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/KafkaEventData.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerBindingStrategy.cs

Changes
* Remove KafkaEventData(byte[]) ctor
* Add custom deserialisation example to sample function project
* Add binding to string in sample function project
Fixes #43 
Addresses `string` binding from #44

Remove KafkaEventData(byte[]) ctor

---

samples/dotnet/KafkaFunctionSample/AvroSpecificTriggers.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerFactory.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/MultiItemTrigger.cs

Turns out task 3 of #44 doesn't require any additional work; we got it for free. Added samples demonstrating

Adding sample cases for byte[] and byte[][] triggers

---

.gitignore
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/EndToEndTestExtensions.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTestFixture.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaOutputFunctions.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj

Changes
* Fixes the topic creation in e2e text fixture. There was a problem getting the properties and topic with 1 partition was being automatically created
* Fixes timing issue in e2e caused by output binder send events only when flushed

Fix e2e bug introduced by batch message output

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAsyncCollector.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaAsyncCollectorTests.cs

The destination Kafka topic can be decided during the function execution (`KafkaEventData.Topic = "foo";`). Therefore I am removing the argument null check at the constructor and associated test.
CI should pass again.

KafkaAsyncCollector doesn't require topic in ctor

---

samples/dotnet/KafkaFunctionSample/AvroGenericTriggers.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerBindingStrategy.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerBindingStrategyTest.cs

**Changes**
* Polishes the automatic binding of `topic, partition, offset, timestamp and key` in trigger functions
* Sample function modified to illustrate how to use automatic binding
Sample:
```csharp
[FunctionName(nameof(PageViews))]
public static void PageViews(
[KafkaTrigger("LocalBroker", "pageviews", AvroSchema = PageViewsSchema, ConsumerGroup = "azfunc")] KafkaEventData[] kafkaEvents,
long[] offsetArray,
int[] partitionArray,
string[] topicArray,
DateTime[] timestampArray)
{
// offsetArray will contain the offsets of each message
// same for partitionArray, topicArray and timestampArray
}
```
Part of #44

Add trigger binding to offset, timestamp as params

---

azure-pipelines.yaml
build/common.props

I update the build pipeline to automate the packaging nuget and start creating release pipeline for the release. 
* build/test packaging nuget package. 
* upload to drop folder to share with release pipeline.
* to enable the `-preview` stuff, it looks not good. If you guys know the smart way, please let me know. 
* Build a Release Pipeline to publish nuget package 
For the push the package to the nuget.org, we need Azure Functions team's key for the namespace. Microsoft.Azure.WebJobs.*.  I'm talking with them about it.

Pack the nuget package and publish to the drop for release pipeline

---

build/common.props

Sorry, I want to get back the Version Suffix according to the Brandon advice. 
Now I know how to use it.  It is ignored for the CI pipeline if you don't specify the Version Suffix. 
However, under the development, you might use nuget package for testing.  In this case, 
you can set the Version Suffix then, it will be '0-0-0-alpha71'  71 is build id.  
It is automatically create/publish nuget package to private nuget repo. 
If you can see the pipeline example, it is on the our project Azure DevOps, Publish-Nuget-To-Private.CI. Once this PR gets merged, the pipeline can be available for the member of developer. 
Regards, 
Tsuyoshi

Version Suffix for CI

---

samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleProducer/ConsoleProducer.csproj
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj

As Confluent.Kafka gets ready to release 1.0 I want to keep us close as possible to the release bits in order to identify potential problems as early as possible.
This PR updates the dependencies to what seems to be the last RC before 1.0 release.
Fixes #62

Update to Confluent.Kafka RC3

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttribute.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducer.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerProvider.cs

Targeting #11 
Would appreciate review of this; since we're just piping them down in to the Kafka `ProducerConfig` object, I'm not sure there's any additional work needed.

Add properties for producer configuration to Output Binding Attribute definition

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj

This PR is related the style of the standard of nuget publishing. 
The related issue is : https://github.com/Azure/azure-functions-kafka-extension/issues/66
I change the csproj  file to fit the standard. 
This is the example of the standard. 
https://github.com/Azure/azure-functions-eventgrid-extension/blob/dev/src/EventGridExtension/EventGridExtension.csproj
On the issue, it said that, we need strong name for our library, however, it is not mandatory (recommended) and we have 3rd party library which we need strong name library as well. 
We have 2 library which is not support strong name. 
* Confluent.Kafka
* Confluent.SchemaRegistry.Serdes
We can use Confluent.Kafka.StrongName instead, however, not for Confluent.SchemaRegistry.Serdes. 
So I decide go without strong name sign.

Apply the change for fit the syle of the standard

---

README.md
samples/dotnet/KafkaFunctionSample/AvroSpecificTriggers.cs
samples/dotnet/KafkaFunctionSample/ProduceStringTopic.cs
samples/dotnet/KafkaFunctionSample/RawTypeTriggers.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/BrokerAuthenticationMode.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/BrokerProtocol.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaOptions.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Extensions/ConfigurationExtensions.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListenerFactory.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttribute.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaListenerConfiguration.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttribute.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/KafkaListenerForTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerFactoryTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaProducerFactoryTest.cs

Changes in this PR:
- Added basic authentication for trigger and output bindings #67 
- Exposing AutoCommitIntervalMs setting in host.json file
- Added tests for Kafka consumer/producer configuration based on attributes
- Added documentation on connecting to a secure Kafka broker
Pending:
- Add secure connection to e2e tests #77

Add basic authorization for brokers

---

azure-pipelines.yaml
build/common.props

This moves the extension version to 1.0.0-alpha, for publishing
Also removing the package signing as part of the regular build step as this has been moved to the release flow.

Updating extension version and removing package signing

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj

fabio recommend me to have a pdb inclusion and source link. 
This PR is for pdb.  This configuration include the pdb file into the dll with affordable size. 
It helps a debugging a lot. azure web jobs project do the same thing. 
https://github.com/Azure/azure-webjobs-sdk-extensions/blob/7fcca7f5ce44c28b1bc9cff51592737c95c78c5f/build/common.props#L12
This conversation is easy to understand what happens. 
https://twitter.com/kirillosenkov/status/1007052524946255872?lang=en

Adding pdb files to the dll

---

README.md
samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleConsumer/MagicAvroDeserializer.cs
samples/dotnet/ConsoleConsumer/Program.cs
samples/dotnet/ConsoleProducer/ConsoleProducer.csproj
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Serialization/SerializationHelper.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/KafkaListenerForTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerAttributeBindingProviderTest.cs

Updating the dependency of Confluent.Kafka to official v1.0.0.
Remarks:
- There is no clean solution for Avro serializers, the library offers sync over async for now
- Update the readme, removing the version we depend on since it is not beta anymore
Would be nice to test other languages too (@TsuyoshiUshio, @priyaananthasankar)
Fixes #75

Update Confluent.Kafka to version 1.0.0

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaEventDataConvertManager.cs

Fixed a bug where a trigger using GenericRecord (avro) would not be correctly called.

Fix bug with GenericRecord trigger being null

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs

This change allows the SSL* settings in the KafkaTrigger attribute to be fetched from config/environment variables/nameresolver like the other values.

Allow SSL certificate attribute settings to be resolved from config

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/AzureFunctionsFileHelper.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.targets
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/AzureFunctionsFileHelperTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs

Running a function using the extension in Azure current does not work. The host cannot start because the extension fails to load librdkadka.
After investigation, I believe this happens because the current directory when running in Azure is not the function output folder (which is true when debugging locally). To handle this, I am loading the library from an explicit location.
I am using environment variables, and known information (i.e. d:\Home\sites\wwwroot being the base path) to resolve the location. I wonder if there is a better way to do it.
I also include the cacert.pem file as part of the nuget package as this is a requirement when using Event Hubs with Kafka header.
Fixes #110

Fix librdkafka not found when running in Azure

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/MultipleItemFunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/SingleItemFunctionExecutor.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs

Function executions are dispatched in two ways:
- Multiple items 
- Trigger function receives a collection of events (from 1 or more partitions)
- A single function call is executed for whole batch
- Checkpoint happens after the function call returns
- Single items
- Trigger function receives one event
- One function call per event, parallelize by partition
- Checkpoint happens after all function calls succeeded
With the upcoming introduction of a scaler, the fact that the checkpoint for single dispatch happens only once all calls are completed causes a delay in updating the consumer lag, specially if the function execution takes too long and the batch size is big.
To have a more accurate consumer lag metrics the following changes for single dispatching are being introduced:
- 1 task per …

Commit single dispatch after each function call

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/AzureFunctionsFileHelper.cs

This fixes the incorrect error when running the extension locally:
"Librdkafka initialization: did not attempt to load librdkafka because the desired file does not exist: '{librdkafkaPath}'"

Supress Libradkafka load error log message in development

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/AzureFunctionsFileHelper.cs

Adding the option to set where the librdkafka is located, in case the built-in resolution fails.

Add setting to load librdkafka from specific path

---

samples/python/README.md

fix: wrong parameter order for Python command

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs

This is requested from this issue. 
https://github.com/Azure/azure-functions-kafka-extension/issues/148
Enabling Binding expression for the `topic` and `consumer group`. 
* [Binding expressions - app settings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns)
We can configure the kafka trigger with `%NAME%` and you can configure the value on your app settings or local.settings.json.
```csharp
[FunctionName(nameof(StringTopic))]
public static void StringTopic(
[KafkaTrigger("%broker%", "stringTopic", ConsumerGroup = "%consumerGroup%")] KafkaEventData<string> kafkaEvent,
ILogger logger)
{
logger.LogInformation(kafkaEvent.Value.ToString());
}
```

Enable app setting binding expression for consumer group and topic

---

README.md
build/common.props
samples/README.md
samples/dotnet/KafkaFunctionSample/SimpleKafkaTriggers.cs
samples/dotnet/README.md

I upgrade the Kafka extension for the next release with EventHubs sample. 
* Add EventHubs sample 
* Update the documentation related `ca.cert` except for language samples. 
* Languages sample/documentation update
For language support, we don't need the `ca.cert` anymore, however, for the testing, we need published nuget.
I'll do this after publish the new version.

Bump version and Add EventHubs sample

---

samples/dotnet/KafkaFunctionSample/SimpleKafkaTriggers.cs
samples/dotnet/README.md
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttributeBinding.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttributeBindingProvider.cs

Enabled to reference the KafkaOutput binding to use reference resolution. 
_functions_
```csharp
[FunctionName(nameof(SampleProducer))]
public IActionResult SampleProducer(
[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
[Kafka(
"LocalBroker",
"%EHTOPIC%",
Username = "$ConnectionString",
Password = "%EventHubConnectionString%",
Protocol = BrokerProtocol.SaslSsl,
AuthenticationMode = BrokerAuthenticationMode.Plain)] out KafkaEventData<string>[] kafkaEventData,
ILogger logger)
{
: 
}
```
_local.settings.json_
```json
{
"IsEncrypted": false,
"Values": {
"AzureWebJobsStorage": "None",
"FUNCTIONS_WORKER_RUNTIME": "dotnet",
"LocalBroker": "YOUR_NAMESPACE.servicebus.windows.net:9093",
"EHTOPIC": "myeventhub",
"EventHubConnectionString": …
```

Output Binding Topic Support AppSettings

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj

The Release pipeline has been failed. The root cause was, LicenseUrl becomes, deprecated. That prevents to create nuget file. 
For more details, refer to 
* [Adding license details to NuGet packages](https://www.flexlabs.org/2019/05/adding-license-details-to-nuget-packages)
* [Azure Functions Host: package.props](https://github.com/Azure/azure-functions-host/blob/8abc744eb19e382badcb266215006432ff4939ad/build/package.props)
```cmd
dotnet pack -o . --include-symbols src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
All projects are up-to-date for restore.
Microsoft.Azure.WebJobs.Extensions.Kafka …
```

Remove the PackageLicenseUrl for deprecation

---

samples/dotnet/KafkaFunctionSample/.vscode/extensions.json

ms-vscode.csharp is now ms-dotnettools.csharp

Update C# extension name

---

.gitignore
README.md
samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleProducer/ConsoleProducer.csproj
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/KafkaFunctionSample/SimpleKafkaTriggers.cs
samples/dotnet/KafkaFunctionSample/host.json
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaOptions.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/MultipleItemFunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/SingleItemFunctionExecutor.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs

This PR includes
* Upgrade Confluent.Kafka 1.5.2
* Adding Following Libkafka properties with default values. 
* Add Log to identify if users use SingleFunctionExecutor or MultipleFunctionExecutor
* Redirect Libkafka Log to the ILogger
|Setting|librdkafka property|default|Trigger or Output|
|-|-|-|-|
|LibkafkaDebug|debug|null|Both
|MetadataMaxAgeMs|metadata.max.age.ms|180000|Both
|SocketKeepaliveEnable|socket.keepalive.enable|true|Both
The reason of the default settings, refer to this [issue](https://github.com/Azure/azure-functions-kafka-extension/issues/187)
For the log of FunctionExecutor, I'd like to know if a user uses Single or Multiple Function Executor for diagnosing an issue.
If there is a better place, please let me know.
Currently, the Libkafka message is showed up standard …

Upgrade 1.5.2 and improve debugging

---

build/common.props
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj

I'd like to pre-release to fix the `GroupCoordinator: *.*.*.*:9092: 1 request(s) timed out: disconnect` for this update solve the issue. 
That issue Could happens Azure Backed infractructure e.g. EventHubs,  HDInsights based Kafka.
I reproduce the issue with 3.2.1 with EventHubs with Kafka API. 
With this version, the issue is resolved. 
For the official release, I'll release with Confluent.Kafka library with 1.6.0. However, until then, mitigate the issue by using this version.

Upgrade KafkaLibrary for pre release

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/AzureFunctionsFileHelper.cs

When we use extension bundle, it could possible that the native library is not exists under `wwwroot` on a windows worker. 
I noticed that kusto query returns error on that part for the extension bundle use case. 
So that I made it as warning and add context for the message.

Change the log level since it could happens when we use extension bundles

---

docs/public-documentation/Output.md
docs/public-documentation/Trigger.md

Added examples section for Kafka trigger and output binding public documentation. This includes adding examples for processing single as well as batch events.
Added code snippets of all supported runtimes for azure functions.

Added Examples Section in Trigger and Output

---

Microsoft.Azure.WebJobs.Extensions.Kafka.sln
README.md
docs/public-documentation/Trigger.md
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaOptions.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs

- Exposes librdkafka "auto.offset.reset" property as AutoOffsetReset in KafkaOptions. This also allows the property to be set using extension settings in host.json for functions.
- Allows only two values for the property - Latest and Earliest. Default: Earliest.
- Unit test for default and AutoOffsetReset = Latest case. 
- Updated Documentation.
Based on #216

Exposing AutoOffsetReset property in KafkaOptions

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaProducerFactoryTest.cs

For Kafka output binding function, the extension logs were not being collected in application insights. In this PR, we have fixed this issue.

Fixing issues related to Application Insights Logging

---

samples/java/eventhub/src/main/java/com/contoso/kafka/avro/generic/KafkaTriggerAvroGeneric.java

Kafka extension currently supports the key in trigger and output bindings.
For the edge case when Generic Avro for java it's passed as metadata and there is no direct access.
For showcasing how can key value can be accessed the samples function is created
- Doesn't requires any unit test case
- Doesn't require any E2E test case

adding the sample for accessing key in java function with avro

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerAttributeBindingProviderTest.cs

The SslCertificateLocation, SslKeyLocation and SslCaLocation attributes require the absolute path of certificate and keys respectively.  This PR makes sure that the path is absolute and fixes https://github.com/Azure/azure-functions-kafka-extension/issues/321

Bug Fix for fail to load certificate location for KafkaTrigger

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerAttributeBindingProviderTest.cs

If SSLCaLocation, SSLKeyLocation or SslCertificateLocation is null, then it throws the error that location is invalid. 
This PR fixes this bug.

Bug Fix for the file location error

---

test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs

Fixing the time increase in E2E tests after the confluent library upgrade. 
Setting session.timeout.ms to 10 secs for all E2E tests.

Fix for E2E pipeline

---

README.md
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttribute.cs
src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaProducerFactoryTest.cs

Adding the support for linger.ms configuration for the customer for output binding.
A commonly adjusted configuration property on the producer is LingerMs - the minimum time between batches of messages being sent to the cluster. Larger values allow for more batching, which increases throughput. Smaller values may reduce latency. The tradeoff is complicated somewhat as throughput increases though because a smaller LingerMs will result in more broker requests, putting greater load on the server, which in turn may reduce throughput.
This change doesn't requires the new unit test cases nor the e2e test cases.

Adding support for Linger.ms

---

azure-pipelines.yaml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Extensions.Tests.Common/Microsoft.WebJobs.Extensions.Tests.Common.csproj

[Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) requires dotnet core 3.1 to be installed in the pipeline. This PR adds tasks to install dotnet core 3.1 and dotnet 6.0 before running tests.
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=139443&view=results

Fixing pipeline error

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs

Issue:
Currently the End-to-End test for Retry checks if an exception is logged from the kafka function exactly Number of Retries + 1 times. Since the last upgrade, WebJobs SDK has added an additional log after all retires are exhausted to capture the last error throw. This would mean that the actual number of times the exception is logged would increase by 1 for the above test scenario - Leading to the failure of the test in case of WebJobs SDK upgrade. PR link - [https://github.com/Azure/azure-webjobs-sdk/pull/2914](https://github.com/Azure/azure-webjobs-sdk/pull/2914)
Solution:
To remove the dependency on the number of times the exception is logged - This PR introduces a change to look at the actual number of executions of the function from the logs. This is done to unblock the future …

Improving Retry Test for Webjobs Version Upgrade

---

azure-pipelines.yaml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Common/Queue/QueueManager/EventHubQueueManager.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/Facts/IgnoreOnDisableConfluentTestsFlagFact.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/Facts/IgnoreOnDisableEventHubsTestsFlagFact.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/JavaConfluentAppTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/JavaEventhubAppTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/PythonConfluentAppTest.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Tests/PythonEventhubAppTest.cs

The PR contains the following changes - 
1. Re-enabling the Confluent Language End to End test cases which were disabled here - #447 
2. Adding flags in the pipeline to easily enable and disable tests in CI pipeline for future.
3. Improved logging for EventHubQueueManager.

Re-Enabling Confluent Tests and Adding Flags to disable Lang E2E tests from Pipeline

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaTopicScaler.cs
test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTopicScalerTest.cs

Hello everyone,
The KafkaTargetScaler is using the obsolete [ScaleMonitorDescriptor](https://github.com/Azure/azure-webjobs-sdk/blob/8ef02d5a3a78056f9ec5a2bc9459b9600c0a0309/src/Microsoft.Azure.WebJobs.Host/Scale/ScaleMonitorDescriptor.cs#L19) constructor without the functionId parameter.
```csharp
[Obsolete("This constructor is obsolete. Use the version that takes function id instead.")]
public ScaleMonitorDescriptor(string id)
{
Id = id;
}
public ScaleMonitorDescriptor(string id, string functionId) : this(id)
{
FunctionId = functionId;
}
```
```csharp
```
When target scaling is enabled (by default) the [ScaleManager](https://github.com/Azure/azure-webjobs-sdk/blob/8ef02d5a3a78056f9ec5a2bc9459b9600c0a0309/src/Microsoft.Azure.WebJobs.Host/Scale/ScaleManager.cs#L237-L238) compares the …

Fix scale monitor descriptor function id

---

eng/ci/public-build.yml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/start-kafka-test-environment.sh

Updated the start kafka container script to explicitly install the docker compose. Tested the build succeeds with build on the branch. The pipeline sometimes still faces the issue of request throttling from docker hub.

Fix Docker Compose Failure in Build Pipeline

---

samples/dotnet/ConsoleConsumer/ConsoleConsumer.csproj
samples/dotnet/ConsoleConsumer/MagicAvroDeserializer.cs
samples/dotnet/ConsoleProducer/ConsoleProducer.csproj
samples/dotnet/ConsoleProducer/Program.cs
samples/dotnet/ConsoleProducer/ProtobufTopicProducer.cs
samples/dotnet/ConsoleProducer/StringTopicProducer.cs
samples/dotnet/KafkaFunctionSample/KafkaFunctionSample.csproj
samples/dotnet/SampleHost/SampleHost.csproj

Changes made to dotnet inproc sample:
- Removed unused directives from sample consumer and producer console apps
- Updated all packages in project to recent versions (taken from [NugetGallery](https://www.nuget.org/packages))
- Migrated functions host v3 to v4 (ref: [Migrate apps from Azure Functions version 3.x to 4.x | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net8%2Cazure-cli%2Cwindows&pivots=programming-language-csharp))
Tested using docker run local kafka server (https://wurstmeister.github.io/kafka-docker/)

Update framework and package versions used in dotnet in-proc sample

---

src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaEventDataConvertManager.cs

Allow tombstone events to appear as empty arrays when using `byte[][]` parameter in KafkaTrigger
Solves https://github.com/Azure/azure-functions-kafka-extension/issues/545.

Allow tombstone events to appear as empty arrays 

---

test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/kafka-singlenode-compose.yaml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/start-kafka-test-environment.sh

Confluent cp-kafka image started using Apache Kafka 4.0.x from June 11 which removes dependency on zookeeper. This PR has changes to upgrade the end-to-end tests to keep using the latest cp-kafka image instead of pinning a specific older version. Also adds a retry mechanism for end-to-end tests instead of passively waiting for the kafka containers to start.
Notes and references:
- Created CLUSTER_ID using [/bin/kafka-storage.sh](https://docs.confluent.io/platform/current/kafka-metadata/config-kraft.html#generate-format-ids)
- [Confluent platform and Apache Kafka compatibility](https://docs.confluent.io/platform/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility)
- [Reference example config for kafka with …

Remove Zookeeper dependency in end to end tests

---

eng/ci/official-build.yml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/Confluent/pom.xml
test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/EventHub/pom.xml

As the name says.
[Core tools preview version](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.3.0-preview1) is causing official pipeline failures. Hence pinning it to version from last week.
[azure functions maven plugin](https://github.com/microsoft/azure-maven-plugins/releases/tag/azure-functions-maven-plugin-v1.36.0) update to latest release from 1.19.

Update azure functions maven plugin package and pin core tools version
