- azure-pipelines.yaml
Adding component governance to all branches and pull requests (#12)
> Add component governance to all branches and PRs

- README.md
- samples/dotnet/KafkaFunctionSample/AvroGenericTriggers.cs
- samples/dotnet/KafkaFunctionSample/AvroSpecificTriggers.cs
- samples/dotnet/KafkaFunctionSample/ProduceStringTopic.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaWebJobsBuilderExtensions.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/IKafkaProducerProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducer.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerProvider.cs
Changes
* Added logging to Kafka producer (output binding)
* Renamed KafkaProducerManager &rarr; KafkaProducerProvider
> Add log to Kafka producer

- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/GlobalSuppressions.cs
Signed-off-by: Kenneth Ham <kenneth.ham@microsoft.com>
> [v1.0.5.3] Removed `GlobalSuppressions.cs`

- README.md
Updated the status badge to point to new build project.
> Update status badge with new CI

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
The License link was wrong (not our LICENSE but official one) 
https://go.microsoft.com/fwlink/?linkid=2028464
Fabio told me.
> fix License link

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
Added the CA certificate location to the config and overwrite the default value with the one from the function binding (if defined)
> Ca Certificate from function binding

- test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/KafkaEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/TriggerFunctions.cs
Add missing end to end tests for generic avro trigger function
> Add e2e test scenario with generic avro reader

- README.md
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaAttribute.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaListenerConfiguration.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttribute.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaProducerFactoryTest.cs
Adds settings for SslCertificateLocation, SslKeyLocation, SslKeyPassword to both listener and producer and the respective attributes.
Closes #105
> Add settings for SslCertificateLocation, SslKeyLocation, SslKeyPassword

- README.md
- build/common.props
> - Update common.props

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/AzureFunctionsFileHelper.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
This PR has the following fix/improvements:
- Fix null reference exception that happens when terminating the listener due to error. The functionExecutor can be null
- Ensuring all disposable objects are disposed during listener cleanup
- Calls to InitializeLibrdKafka need to wait until the library is loaded before making any call using it. Added a lock to make callers wait.
- Add more information to librdkafka library loading
> Improve listener terminating

- README.md
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
Changes:
- Add section Connecting to Confluent Cloud in Azure in documentation
- Add better resolution of SslCaLocation to work during development and Azure hosting
> Improve support to Confluent Cloud in Azure

- samples/powershell/extensions.csproj
- samples/powershell/host.json
- samples/powershell/kafkapwsh/function.json
- samples/powershell/kafkapwsh/run.ps1
- samples/powershell/producewithccloud.ps1
Implement kafka with PowerShell, consumer and produce sample.
> powershell sample

- README.md
- binding-library/java/src/main/java/com/microsoft/azure/functions/kafka/annotation/KafkaTrigger.java
- samples/java/README.MD
- samples/java/install_extension.sh
- samples/java/src/main/java/com/contoso/kafka/FunctionOutput.java
- samples/java/src/main/java/com/contoso/kafka/TriggerFunction.java
- samples/java/src/repo/com/microsoft/azure/functions/azure-functions-java-library-kafka/maven-metadata-local.xml
This PR is substitute of this PR. The commits are the same. However, the PR doesn't trig the CI. For the detail, please refer the PR that is already approved. 
https://github.com/Azure/azure-functions-kafka-extension/pull/136
> Add Cardinality Support

- README.md
- samples/README.md
- samples/container/kafka-function/Dockerfile
- samples/container/kafka-function/extensions.csproj
- samples/java/confluent/extensions.csproj
- samples/java/confluent/install_extension.ps1
- samples/java/confluent/install_extension.sh
- samples/java/confluent/src/repo/com/microsoft/azure/functions/azure-functions-java-library-kafka/1.0.0/azure-functions-java-library-kafka-1.0.0.pom
- samples/java/confluent/src/repo/com/microsoft/azure/functions/azure-functions-java-library-kafka/maven-metadata-local.xml
- samples/java/local/extensions.csproj
- samples/java/local/install_extension.ps1
- samples/java/local/install_extension.sh
- samples/javascript/extensions.csproj
- samples/powershell/extensions.csproj
- samples/python/extensions.csproj
- samples/typescript/kafka-trigger/extensions.csproj
Upgrade the sample library NuGet to the 3.0.0
I tested on the new 3.0.0 that makes sure it works.
> Upgrade the sample library to the 3.0.0

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/AzureFunctionsFileHelperTest.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/AzureEnvironment.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaProducerFactoryTest.cs
Fixed the issue by reusing existing code to resolve the location of the file. If the file is not found, the original value for the attribute value is used.
Added additional unit tests to cover these scenarios
> Fixed issue 157 where attribute binding would not load files correctly

- build/common.props
Bump the version for the release. 
I wanted to make it for 3.2.0, however, I missed the bump the tag.
> Upgrade Version 3.2.1

- samples/README.md
I updated Kafka Extension version in sample/README.md
> Update Kafka Extension version

- build/common.props
Adding Header Future to this pre-release.
> Update the version for pre-release 3.3.1-PRE2

- update-version.ps1
Usage `.\update-version.ps1 -oldVersion 1.6.0-PRE4 -newVersion 1.6.3 -oldExtensionVersion 3.3.1-PRE2 -newExtensionVersion 3.3.1`
> Adding version up script

- .github/release-drafter.yml
This change keep consistent the release title for draft pr.
> Remove version prefix for release pipeline(GitHub Action)

- .github/release-drafter.yml
- .github/workflows/release.yml
Update the Release labels. 
Update the PAT for automated release.
> Upgrade GitHubActions

- samples/javascript/Dockerfile
- samples/javascript/extensions.csproj
The Node sample was old especially Dockerfile installing librdkafka is wrong. 
That is automatically installed by `func extensions install`
> Update node sample

- azure-pipelines.yaml
Summary
Modifies pipeline to generate SBOM in ADO.
Pull request checklist
Additional information
Additional PR information
> adding sbom stage in pipeline

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerBindingStrategy.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerBindingStrategyTest.cs
Adding the headers in binding for different languages
> adding the binding for supporting headers

- samples/README.md
Removing Confluent Cloud Credentials from README.md
> Removing Confluent Cloud Credentials from README.md

- azure-pipelines.yaml
- samples/javascript/UsersTrigger/function.json
- samples/python/KafkaTrigger/function.json
- samples/python/KafkaTriggerMany/function.json_
- samples/python/extensions.csproj
- samples/typescript/kafka-trigger/.devcontainer/Dockerfile
- samples/typescript/kafka-trigger/.devcontainer/devcontainer.json
- samples/typescript/kafka-trigger/UsersTrigger/function.json
- samples/typescript/kafka-trigger/UsersTriggerMany/function.json
- samples/typescript/kafka-trigger/extensions.csproj
- samples/typescript/kafka-trigger/local.settings.json.example
- samples/typescript/kafka-trigger/package-lock.json
- samples/typescript/kafka-trigger/package.json
Currently, there are samples in the Kafka extension repo where we are setting the configuration in function.json, which should be in local.settings.json. This needs to be done to guide new customers to adopt the correct & recommended approach until we add the check for the config.
> Modifying function.json in samples to use local.settings.json

- samples/dotnet/Confluent/Confluent.csproj
- samples/dotnet/EventHub/EventHub.csproj
- samples/java/confluent/extensions.csproj
- samples/java/eventhub/extensions.csproj
- samples/java/local/pom.xml
- samples/javascript/extensions.csproj
- samples/powershell/KafkaOutputManyWithHeaders/run.ps1
- samples/powershell/KafkaOutputWithHeaders/run.ps1
- samples/powershell/extensions.csproj
- samples/python/extensions.csproj
- samples/typescript/extensions.csproj
1. Removed test libraries for java in local folder. 
2. Renaming powershell output binding functions to correct ones
3. Correcting Kafka extension nuget package version to 3.4.0
> Correcting the Samples

- samples/typescript/KafkaAvroGenericTriggerMany/function.confluent.json
- samples/typescript/KafkaAvroGenericTriggerMany/function.eventhub.json
- samples/typescript/KafkaAvroGenericTriggerMany/index.ts
- samples/typescript/KafkaTriggerAvroGeneric/function.confluent.json
- samples/typescript/KafkaTriggerAvroGeneric/function.eventhub.json
- samples/typescript/KafkaTriggerAvroGeneric/index.ts
Avrosamples for Generic Records Typecript
> Avrosamples for Generic Records Typecript 

- samples/WalletProcessing_KafkademoSample/ReadMe.md
Updates yaml values for Azure samples job to pick up.
> fixed yaml values

- samples/WalletProcessing_KafkademoSample/ReadMe.md
Reverts Azure/azure-functions-kafka-extension#355
> Revert "fixed yaml values"

- samples/WalletProcessing_KafkademoSample/ReadMe.md
Note: This Readme file needs to be pushed from dev branch to main.
> Mykafkabranch

- build/common.props
- Update Kafka Extension from 3.8.0 to 3.9.0
> Update Version from 3.8.0 to 3.9.0

- .github/workflows/codeql.yml
Adding CodeQl workflow for code in java language which includes Samples and Functions Apps.
> Adding CodeQL Workflow for Java

- .github/workflows/codeql.yml
- azure-pipelines.yaml
changing cron to run at weekly schedule
> changing cron to run at weekly schedule

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerFactory.cs
Added resolving for the parameter SslKeyPassword for the producer (output binding).
> Fixed inconsistency between consumer and producer config

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/SingleItemFunctionExecutor.cs
Not committing msg in single mode if cancellation is requested.
> Fixing Msg commit for Cancellation Scenarios

- build/common.props
Changing extension version from 3.9.0 to 4.0.0
> Updating extension version to 4.0.0

- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/Scaler/KafkaScalerProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaScalerProviderTest.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerAttributeBindingProviderTest.cs
Added some basic UTs and cleanup for SSL PEM attribute handling.
> Unit tests and Improved handling for SSL PEM attributes

- test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/Confluent/extensions.csproj
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/Confluent/pom.xml
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/EventHub/extensions.csproj
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/FunctionApps/java/EventHub/pom.xml
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Extensions.Tests.Common/Microsoft.WebJobs.Extensions.Tests.Common.csproj
* Bumping up various package dependencies
* build fix
* nit
> [Cherry-pik]Bumping up various package dependencies in tests

- eng/ci/official-build.yml
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/start-kafka-test-environment.sh
Settings -> librdkafka property table entry was incorrect for `ReconnectBackoffMs`
https://github.com/confluentinc/librdkafka/blob/25db856554c947d21c0a1892aef22938a1c8dc82/CONFIGURATION.md?plain=1#L35-L36
> Corrects 1 line error in main README.md: reconnect.backoff.max.ms -> reconnect.backoff.ms

- README.md
- build/common.props
- eng/ci/public-build.yml
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Config/KafkaExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Listeners/KafkaListener.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/FunctionExecutorBase.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaEventDataConvertManager.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/KafkaTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/MultipleItemFunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Extensions.Kafka/Trigger/SingleItemFunctionExecutor.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/Helpers/KafkaListenerForTest.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaListenerTest.cs
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests/KafkaTriggerAttributeBindingProviderTest.cs
Cherry Picks for the PRs #543 #517 #544 #546
> Cherry Picks for version 4.1.0

- eng/cd/official-release.yml
- eng/cd/templates/approve.yml
- eng/cd/templates/publish.yml
- eng/cd/templates/validate.yml
- eng/ci/code-mirror.yml
* add yml files
* updated sign-files task to sync with master
* added release tags to mirror
* updated release yml files
---------
> [Cherry pick] Add 1ESPT release pipeline

- eng/cd/templates/approve.yml
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v1?view=azure-pipelines
> Update release approvers

- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/server/java8/Dockerfile
- test/Microsoft.Azure.WebJobs.Extensions.Kafka.LangEndToEndTests/server/python38/Dockerfile
* Update Docker base image to specific SHA256 digest
* Update Dockerfile to use specific image SHA
* Add comment for base image in Dockerfile
> [Cherry-pick]Update Docker base images in tests to specific SHA256 digest (#577)

- eng/ci/code-mirror.yml
Adding tags based trigger in code mirror pipeline.
> Adding tags based trigger in code mirror pipeline. (#596)
